version: '3.8'

services:
  hb-campaign:
    depends_on: 
      - mysql
    build:
      context: .
      dockerfile: Dockerfile.multistage
    container_name: hbCont
    hostname: hb-campaign
    networks:
      - mynet
  mysql:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    container_name: mysqlCont
    hostname: db
    environment:
      - MYSQL_ROOT_PASSWORD=12345
    networks:
      - mynet
    ports:
      - 3306:3306
      - 8080:8080
networks:
  mynet:
    driver: bridge