version: '3.8'

services:
  hb-campaign:
    depends_on: 
      - mysql
    build:
      context: .
      dockerfile: Dockerfile.multistage
    container_name: hbCont
    hostname: hb-campaign
    networks:
      - mynet
    deploy:
      restart_policy:
        condition: on-failure
  mysql:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    container_name: mysqlCont
    hostname: db
    networks:
      - mynet
    ports:
      - 3306:3306
      - 8080:8080

networks:
  mynet:
    driver: bridge