// Code generated by MockGen. DO NOT EDIT.
// Source: .\internal\app\repositories\campaign_repository.go

// Package repositories is a generated GoMock package.
package repositories

import (
	models "hb-campaign/internal/app/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockCampaignRepositoryI is a mock of CampaignRepositoryI interface.
type MockCampaignRepositoryI struct {
	ctrl     *gomock.Controller
	recorder *MockCampaignRepositoryIMockRecorder
}

// MockCampaignRepositoryIMockRecorder is the mock recorder for MockCampaignRepositoryI.
type MockCampaignRepositoryIMockRecorder struct {
	mock *MockCampaignRepositoryI
}

// NewMockCampaignRepositoryI creates a new mock instance.
func NewMockCampaignRepositoryI(ctrl *gomock.Controller) *MockCampaignRepositoryI {
	mock := &MockCampaignRepositoryI{ctrl: ctrl}
	mock.recorder = &MockCampaignRepositoryIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCampaignRepositoryI) EXPECT() *MockCampaignRepositoryIMockRecorder {
	return m.recorder
}

// CreateCampaign mocks base method.
func (m *MockCampaignRepositoryI) CreateCampaign(cc models.CreateCampaign) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCampaign", cc)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCampaign indicates an expected call of CreateCampaign.
func (mr *MockCampaignRepositoryIMockRecorder) CreateCampaign(cc interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCampaign", reflect.TypeOf((*MockCampaignRepositoryI)(nil).CreateCampaign), cc)
}

// GetCampaignByName mocks base method.
func (m *MockCampaignRepositoryI) GetCampaignByName(campaignCode string) (models.Campaign, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCampaignByName", campaignCode)
	ret0, _ := ret[0].(models.Campaign)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCampaignByName indicates an expected call of GetCampaignByName.
func (mr *MockCampaignRepositoryIMockRecorder) GetCampaignByName(campaignCode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCampaignByName", reflect.TypeOf((*MockCampaignRepositoryI)(nil).GetCampaignByName), campaignCode)
}
