// Code generated by MockGen. DO NOT EDIT.
// Source: .\internal\app\repositories\product_repository.go

// Package repositories is a generated GoMock package.
package repositories

import (
	models "hb-campaign/internal/app/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockProductRepositoryI is a mock of ProductRepositoryI interface.
type MockProductRepositoryI struct {
	ctrl     *gomock.Controller
	recorder *MockProductRepositoryIMockRecorder
}

// MockProductRepositoryIMockRecorder is the mock recorder for MockProductRepositoryI.
type MockProductRepositoryIMockRecorder struct {
	mock *MockProductRepositoryI
}

// NewMockProductRepositoryI creates a new mock instance.
func NewMockProductRepositoryI(ctrl *gomock.Controller) *MockProductRepositoryI {
	mock := &MockProductRepositoryI{ctrl: ctrl}
	mock.recorder = &MockProductRepositoryIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProductRepositoryI) EXPECT() *MockProductRepositoryIMockRecorder {
	return m.recorder
}

// CreateProduct mocks base method.
func (m *MockProductRepositoryI) CreateProduct(cp models.CreateProduct) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProduct", cp)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateProduct indicates an expected call of CreateProduct.
func (mr *MockProductRepositoryIMockRecorder) CreateProduct(cp interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProduct", reflect.TypeOf((*MockProductRepositoryI)(nil).CreateProduct), cp)
}

// GetProductByProductCode mocks base method.
func (m *MockProductRepositoryI) GetProductByProductCode(productCode string) (models.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProductByProductCode", productCode)
	ret0, _ := ret[0].(models.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProductByProductCode indicates an expected call of GetProductByProductCode.
func (mr *MockProductRepositoryIMockRecorder) GetProductByProductCode(productCode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProductByProductCode", reflect.TypeOf((*MockProductRepositoryI)(nil).GetProductByProductCode), productCode)
}

// GetProductInitialPriceByProductCode mocks base method.
func (m *MockProductRepositoryI) GetProductInitialPriceByProductCode(productCode string) (models.ProductPrice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProductInitialPriceByProductCode", productCode)
	ret0, _ := ret[0].(models.ProductPrice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProductInitialPriceByProductCode indicates an expected call of GetProductInitialPriceByProductCode.
func (mr *MockProductRepositoryIMockRecorder) GetProductInitialPriceByProductCode(productCode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProductInitialPriceByProductCode", reflect.TypeOf((*MockProductRepositoryI)(nil).GetProductInitialPriceByProductCode), productCode)
}

// GetProductPriceByProductCode mocks base method.
func (m *MockProductRepositoryI) GetProductPriceByProductCode(productCode string) (models.ProductPrice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProductPriceByProductCode", productCode)
	ret0, _ := ret[0].(models.ProductPrice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProductPriceByProductCode indicates an expected call of GetProductPriceByProductCode.
func (mr *MockProductRepositoryIMockRecorder) GetProductPriceByProductCode(productCode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProductPriceByProductCode", reflect.TypeOf((*MockProductRepositoryI)(nil).GetProductPriceByProductCode), productCode)
}

// GetProductStockByProductName mocks base method.
func (m *MockProductRepositoryI) GetProductStockByProductName(productCode string) (models.ProductStock, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProductStockByProductName", productCode)
	ret0, _ := ret[0].(models.ProductStock)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProductStockByProductName indicates an expected call of GetProductStockByProductName.
func (mr *MockProductRepositoryIMockRecorder) GetProductStockByProductName(productCode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProductStockByProductName", reflect.TypeOf((*MockProductRepositoryI)(nil).GetProductStockByProductName), productCode)
}

// UpdateProductPriceByProductCode mocks base method.
func (m *MockProductRepositoryI) UpdateProductPriceByProductCode(productCode string, newPrice float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProductPriceByProductCode", productCode, newPrice)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateProductPriceByProductCode indicates an expected call of UpdateProductPriceByProductCode.
func (mr *MockProductRepositoryIMockRecorder) UpdateProductPriceByProductCode(productCode, newPrice interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProductPriceByProductCode", reflect.TypeOf((*MockProductRepositoryI)(nil).UpdateProductPriceByProductCode), productCode, newPrice)
}

// UpdateProductStockByProductName mocks base method.
func (m *MockProductRepositoryI) UpdateProductStockByProductName(up models.UpdateProductStock) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProductStockByProductName", up)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateProductStockByProductName indicates an expected call of UpdateProductStockByProductName.
func (mr *MockProductRepositoryIMockRecorder) UpdateProductStockByProductName(up interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProductStockByProductName", reflect.TypeOf((*MockProductRepositoryI)(nil).UpdateProductStockByProductName), up)
}
